# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1711728487);
user_pref("app.update.lastUpdateTime.background-update-timer", 1711728727);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1711728607);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1711728367);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.history.last_page_visited", "https://www.google.com/");
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1699208035480");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1699229635480");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.startup.homepage", "https://www.google.com/");
user_pref("browser.startup.homepage_override.mstone", "rv:91.0");
user_pref("browser.urlbar.historyEnabled", false);
user_pref("calendar.timezone.local", "America/New_York");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.distroAddons.check", true);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.e10sMultiBlockedByAddons", true);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20230917130859");
user_pref("extensions.lastAppVersion", "2.53.18.1");
user_pref("extensions.lastPlatformVersion", "60.18.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("gecko.handlerService.migrated", true);
user_pref("gfx.crash-guard.d3d11layers.appVersion", "2.53.18.1");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x2486");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "31.0.15.5123");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", true);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.default_charsets.migrated", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.enabled", false);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.clearOnShutdown.cookies", true);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.passwords", true);
user_pref("privacy.clearOnShutdown.siteSettings", true);
user_pref("privacy.popups.remove_blacklist", false);
user_pref("privacy.sanitize.pending", "[{\"id\":\"shutdown\",\"itemsToClear\":[\"cache\",\"cookies\",\"offlineApps\",\"history\",\"urlbar\",\"formdata\",\"downloads\",\"passwords\",\"sessions\",\"siteSettings\"],\"options\":{}}]");
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("services.blocklist.addons.checked", 1699210314);
user_pref("services.blocklist.clock_skew_seconds", 1196);
user_pref("services.blocklist.gfx.checked", 1699210314);
user_pref("services.blocklist.last_etag", "\"1699196235597\"");
user_pref("services.blocklist.last_update_seconds", 1699210314);
user_pref("services.blocklist.onecrl.checked", 1699210314);
user_pref("services.blocklist.plugins.checked", 1699210314);
user_pref("shell.checkDefaultApps", 11);
user_pref("shell.checkDefaultClient", false);
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
user_pref("suite.migration.version", 10);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
